security:
    providers:
        entity_provider:
            entity:
                class: Ux\Bundle\AdminBundle\Entity\User
                property: username

    password_hashers:
        Ux\Bundle\AdminBundle\Entity\User:
            algorithm: bcrypt

    firewalls:
        admin:
            pattern: ^/admin
            provider: entity_provider
            access_denied_url: ~
            access_denied_handler: ~ #Ux\Bundle\AdminBundle\Security\AccessDeniedHandler

            form_login:
                login_path: ux_admin_security_login
                check_path: ux_admin_security_logincheck
                enable_csrf: true
                #csrf_token_generator: security.csrf.token_manager
                failure_path: ~

            logout:
                path: ux_admin_security_logout
                target: ux_admin_security_login

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 86400
                path: ux_admin_default_index

            switch_user:
                provider: ~
                parameter: _switch_user
                role: ROLE_ALLOWED_TO_SWITCH

