security:
    providers:
        entity_provider:
            entity:
                class: Ux\Bundle\AdminBundle\Entity\User
                property: username

    encoders:
        Ux\Bundle\AdminBundle\Entity\User:
            algorithm: bcrypt

    firewalls:
        admin:
            anonymous: ~
            pattern: ^/admin
            provider: entity_provider
            access_denied_url: ~
            access_denied_handler: ~ #Ux\Bundle\AdminBundle\Security\AccessDeniedHandler

            form_login:
                login_path: ux_admin_security_login
                check_path: ux_admin_security_logincheck
                csrf_token_generator: security.csrf.token_manager
                #success_handler: Ux\Bundle\AdminBundle\Security\LoginSuccessHandler
                #failure_handler: Ux\Bundle\AdminBundle\Security\LoginFailureHandler
                failure_path: ~

            logout:
                path: ux_admin_security_logout
                target: ux_admin_security_login
                #success_handler: Ux\Bundle\AdminBundle\Security\LogoutSuccessHandler
                #handlers: [ Ux\Bundle\AdminBundle\Security\LogoutHandler ]

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 86400
                path: ux_admin_default_index

            switch_user:
                provider: ~
                parameter: _switch_user
                role: ROLE_ALLOWED_TO_SWITCH

