language: php
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        - php: 7.4
          env: SKELETON_VERSION="~4.4.0"
        - php: 7.4
          env: SKELETON_VERSION="~5.2.0"

before_install:
    - phpenv config-rm xdebug.ini || true
    - export VERSION=$(if [ "${TRAVIS_BRANCH}" == "master" ];then echo @dev;else echo "^${TRAVIS_BRANCH}-dev";fi)
    - export PACKAGES=ux/admin-bundle:${VERSION}

install:
    - composer create-project "symfony/skeleton:${SKELETON_VERSION}" flex
    - cd flex

script:
    - composer req "${PACKAGES}"
    - ./bin/console cache:clear
    - ./bin/console assets:install public --symlink --relative
